### ISSUE TITLE
Preflop lookup

### ISSUE THREAD

**Issue by Tjorriemorrie** [worldveil/deuces#10]
Will you be providing the lookup for preflop equity?

**Comment by worldveil** [comment]
I had planned to but never had time. 

it's pretty easy to do that from scratch using this interface, it's essentially just a monte carlo over many random hand rollouts. 

you would need a separate one for each number of players (ie: Q-K offsuit with two players is very strong, whereas with nine players it's much weaker). 

if you submit a PR, I'd gladly review
