### ISSUE TITLE
evaluator.evaluate does not support empty board

### ISSUE THREAD

**Issue by cafawo** [worldveil/deuces#15]
According to evaluator.py line 31, the evaluate function supports an empty board.

However, the function produces an error when providing an empty board (list) or no board.

**Comment by worldveil** [comment]
So it's a hash from the hand length to a function. I originally wrote it because I wanted to add a

```python
def _two(self, cards):
     pass
```

function that used rollouts for preflop scoring, but I never did. 

It wouldn't be a true poker hand rank though (need 5 cards), which is probably why I didn't add it.

**Comment by filostrato** [comment]
I'm utilizing this to evaluate hands for OFC poker variants, wherein one of the rows is a three card hand, which can only evaluate to high card, one pair, two pair, or three of a kind, so I'm probably going to make a `_three` function myself, unless you know of an easy way and want to do it first.
