### ISSUE TITLE
no module named 'card'

### ISSUE THREAD

**Issue by stvogel** [worldveil/deuces#16]
Hi Will, 
thanks for providing this module.

After installing deuces with: pip install deuces and doing: import deuces
I get the error:
`No module named 'card'`

I use python 3.5.2.
Thanks for any help.

By the way, this is also described here: http://stackoverflow.com/questions/40337024/import-error-python-no-module-named-card

**Comment by stvogel** [comment]
Ok, I just tried to used it in the cloned directory.
Now I get the typical python 3-error.
`SyntaxError: Missing parentheses in call to 'print'`

**Comment by great-analyzer** [comment]
It's easier to install Python2.7.13 for deuces.
