### ISSUE TITLE
ImportError: No module named 'card'

### ISSUE THREAD

**Issue by ruttydm** [worldveil/deuces#19]
I just installed deuces with the command:

sudo pip3 install deuces (also tried without sudo but that doesn't work)

But when I do import deuces in a simple script it gives me following error:

Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import deuces
  File "/usr/local/lib/python3.5/dist-packages/deuces/__init__.py", line 1, in <module>
    from card import Card 
ImportError: No module named 'card'

What's the problem and how do I properly install deuces?

Please help me.

**Comment by stefangordon** [comment]
I had the same issue on Python 3.  I ran it through 2to3 and fixed some imports and it is working.

**Comment by great-analyzer** [comment]
I had the same issue on Python3.6.1 on Win10. Tried to convert from Py2 to Py3 and gave up for not trivial. Install Python2.7.13 and problem fixed. Use Python Launcher, Py, and switch between Py2 and Py3 codes are easy.
