### ISSUE TITLE
Deuces Poker Output to Console Corrupted

### ISSUE THREAD

**Issue by gollum18** [worldveil/deuces#24]
I am utilizing deuces in an AI project. I have a client written up for it that utilizes the console for player input and output. This is all well and good, however when I run the client, the output for the card symbols refuses to convert correctly in command prompt. It could just be the logic in my code causing it, but I would appreciate assistance.

Here is an example of what I am seeing.

![error](https://cloud.githubusercontent.com/assets/1782006/24552588/06cc09d0-15f5-11e7-9f3f-2d23d7ff9e1e.PNG)

**Comment by Krogenar** [comment]
Maybe try it in powershell, or some other console window? Maybe something to do with the prettyprint module?

**Comment by worldveil** [comment]
Yeah, I have no idea what that is or what you should really be seeing on a Windows non-Cywin terminal.
