### ISSUE TITLE
Empty board?

### ISSUE THREAD

**Issue by MlKEL** [worldveil/deuces#27]
evaluator.evaluate() function help asserts it accepts empty board. How is this done?

I need to evaluate a hand vs another hand in terms of probability prior to knowing the flop.

Thank you very much.

**Comment by worldveil** [comment]
Ah, that was meant to be something I added for preflop lookup tables. Never ended up doing it. 

It's quite easy to do the rollouts yourself - just do some monte carlo simulations of every conceivable starting 2-card hand and roll out many boards to the river and see who wins. A few million or so should probably do it.
