### ISSUE TITLE
Full house not checking hole cards

### ISSUE THREAD

**Issue by hughpearse** [worldveil/deuces#31]
**Steps to reproduce**
hole1=['Ks', '3d']
hole2=['3h', 'Qs']
board=['2d', '7h', '7s', '2s', '7c']

Feeding these in to the evaluator:
score = evaluator.evaluate(board, hole1)
print evaluator.class_to_string(evaluator.get_rank_class(score))
score = evaluator.evaluate(board, hole2)
print evaluator.class_to_string(evaluator.get_rank_class(score))

**Output**
Player P1-3000 had a Full House. Player P2-3001 had a Full House.

**Problem Description**
Neither player has one of their hole cards in play.

**Comment by Krogenar** [comment]
See this: https://github.com/worldveil/deuces/issues/14
Because the 'best hand' is essentially the board itself, then the hole cards don't come into play.

**Comment by worldveil** [comment]
I can't reproduce, Deuces does exactly what it should here. 

```python
from deuces import Card, Evaluator

evaluator = Evaluator()

# setup cards
hole1=[Card.new('Ks'), Card.new('3d')]
hole2=[Card.new('3h'), Card.new('Qs')]
board=[Card.new('2d'), Card.new('7h'), Card.new('7s'), Card.new('2s'), Card.new('7c')]

# evaluate
score = evaluator.evaluate(board, hole1)
print "player1: score=%d, hand=%s" % (score, evaluator.class_to_string(evaluator.get_rank_class(score)))

score = evaluator.evaluate(board, hole2)
print "player1: score=%d, hand=%s" % (score, evaluator.class_to_string(evaluator.get_rank_class(score)))
```

Those two hands are of identical strength (both rank 262).
