### ISSUE TITLE
Card module?

### ISSUE THREAD

**Issue by rattlehead616** [worldveil/deuces#39]
I was trying to use this library and I kept on getting this error: 

Traceback (most recent call last):
  File "c:\Users\rattl\OneDrive\Desktop\PROJECTS\poker.py", line 1, in <module>
    from card import Card
ModuleNotFoundError: No module named 'card'

**Comment by delagra** [comment]
This module runs on Python 2.x. If you run on 3.x you get this error

**Comment by pmchrist** [comment]
For all the people who stumble upon this issue here, there is a Python3 port of Deuces called Treys (https://github.com/ihendley/treys)

**Comment by worldveil** [comment]
Python3 support added!
