### ISSUE TITLE
python 3.4.4

### ISSUE THREAD

**Issue by jorgealemangonzalez** [worldveil/deuces#8]
I'm trying to use your library in my project but when i import the library as:

> from libraries.deuces import *

the system throws the error:

> Traceback (most recent call last):
>   File "C:\Users\jorge\Desktop\Poker_AI\poker_game\src\poker_game.py", line 6, in <module>
>     from libraries.deuces import *
>   File "C:\Users\jorge\Desktop\Poker_AI\poker_game\src\libraries\deuces\__init__.py", line 1, in <module>
>     from .card import Card 
>   File "C:\Users\jorge\Desktop\Poker_AI\poker_game\src\libraries\deuces\card.py", line 199
>     print Card.int_to_pretty_str(card_int)
>              ^
> SyntaxError: invalid syntax

if i comment the print it shows other errors like : 

> Traceback (most recent call last):
>   File "C:\Users\jorge\Desktop\Poker_AI\poker_game\src\poker_game.py", line 6, in <module>
>     from libraries.deuces import *
>   File "C:\Users\jorge\Desktop\Poker_AI\poker_game\src\libraries\deuces\__init__.py", line 1, in <module>
>     from .card import Card 
>   File "C:\Users\jorge\Desktop\Poker_AI\poker_game\src\libraries\deuces\card.py", line 214
>     print output
>                ^
> SyntaxError: Missing parentheses in call to 'print'

COULD BE A PYTHON VERSION ERROR ??
i try useing python versions: 2.7.6 and 3.3.3 

thanks for all

jorge Aleman Gonzalez

**Comment by worldveil** [comment]
`deuces` works on Python 2.7.x, no port to Python 3.5.x has been made yet. 

If you'd like to port it, please feel free to open a PR.
