### ISSUE TITLE
Evaluator rank class is broken for 5-high straight flushes

### ISSUE THREAD

**Issue by DexGroves** [worldveil/deuces#9]
```python
from deuces import Card, Evaluator


evaluator = Evaluator()

straight_flush = [Card.new(x) for x in ['Ah', '2h', '3h', '4h', '5h']]
four_of_a_kind = [Card.new(x) for x in ['Ah', 'As', 'Ac', 'Ad', 'Kh']]

rank_sf = evaluator.evaluate([], straight_flush)
rank_quads = evaluator.evaluate([], four_of_a_kind)

evaluator.class_to_string(evaluator.get_rank_class(rank_sf))
evaluator.class_to_string(evaluator.get_rank_class(rank_quads))
```

Reports the 5-high SF as a 'Four of a Kind'. I want to fix this with a PR, but I the evaluator code is too fancy for me.

**Comment by worldveil** [comment]
Ah, yes. Note that actually the *rank* being returned is and always has been unique between those two hands:

```
>>> print "Straight flush rank=%d, quads rank=%d" % (rank_sf, rank_quads)
Straight flush rank=10, quads rank=11
```

But you are correct the human friendly method to print out the string version is incorrect, it should be `<=` instead of `<`.

**Comment by DexGroves** [comment]
I was more concerned with `get_rank_class` being broken since I want to use it for OFC. Love that this is now pip installable. Thanks for the quick fix!
